"""Create the simulator's lazy, single-request asset bundle.

The bundle is generated from manifest.json so future simulator assets are picked
up automatically.  The browser still falls back to the individual files if a
bundle is missing or stale.
"""

from __future__ import annotations

import base64
import json
import mimetypes
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "assets" / "simulator" / "manifest.json"
OUTPUT = ROOT / "assets" / "simulator" / "bundle.js"


def asset_paths(value: Any) -> set[str]:
    if isinstance(value, str):
        return {value} if value.startswith("./assets/") else set()
    if isinstance(value, list):
        return set().union(*(asset_paths(item) for item in value))
    if isinstance(value, dict):
        return set().union(*(asset_paths(item) for item in value.values()))
    return set()


def data_url(path: str) -> str:
    source = ROOT / path.removeprefix("./")
    if not source.is_file():
        raise FileNotFoundError(f"Simulator asset not found: {source}")
    mime_type = mimetypes.guess_type(source.name)[0] or "application/octet-stream"
    encoded = base64.b64encode(source.read_bytes()).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def main() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    paths = sorted(asset_paths(manifest))
    assets = {path: data_url(path) for path in paths}
    output = "// Generated by tools/build_simulator_bundle.py. Do not edit manually.\n"
    output += "window.EGGISLAND_SIM_ASSETS = Object.freeze("
    output += json.dumps(assets, ensure_ascii=False, separators=(",", ":"))
    output += ");\n"
    if OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == output:
        print(f"Simulator bundle is current ({len(paths)} assets).")
        return
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Built simulator bundle with {len(paths)} assets: {OUTPUT}")


if __name__ == "__main__":
    main()
